### ISSUE TITLE
Crash with entities that explode next to gravel

### ISSUE THREAD

**Issue by Cat-McCatface** [sky0-1/Flint-Instead-Of-Wood-1.9#2]
Thought it was a conflict with Bullseye (which adds explosive arrows) but on making a fresh world and using vanilla tnt it also crashed in the same way.

Conditions: find a natural gravel vein or make one in creative. Place tnt next to gravel. light 'er up. ??? Profit.

MC: 1.10.2
FlintInsteadOfWood[1.10.2]-7.4
Forge: 2010
log:
[crash-2016-07-13_02.55.32-server.txt](https://github.com/sky0-1/Flint-Instead-Of-Wood-1.9/files/360948/crash-2016-07-13_02.55.32-server.txt)

**Comment by sky0-1** [comment]
Thank you for this report, I reproduced the problem and am fixing it right now

**Comment by sky0-1** [comment]
Fixed in 7.5
